### ISSUE TITLE
Error parsing FEED packet

### ISSUE THREAD

**Issue by schendstok** [danielpaulus/quicktime_video_hack#38]
Hi,

The program works very well, but in certain situations I do get an error message on the command line output: Error parsing FEED packet: unknown magic type:ttas (0x73617474)

The video does still seem to play fine though.
My setup: Debian 10 Buster and streaming video from an AppleTV (over the USB-C developer port on the back). The error messages happen when playing videos on YouTube on the Apple TV.

**Comment by DanielPaulusContentful** [comment]
Interesting! I did not know it works with AppleTV :-D 
Can you run post verbose logs? I would like to know what is being sent there by the Apple TV.

Also, let me patch the code so it only prints a warning instead of a Fatal.

**Comment by schendstok** [comment]
{"level":"info","msg":"Starting Gstreamer..","time":"2020-01-29T22:35:16+01:00"}
{"level":"info","msg":"Gstreamer is running!","time":"2020-01-29T22:35:16+01:00"}
{"level":"info","msg":"Device 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' USB connection ready","time":"2020-01-29T22:35:17+01:00"}
{"level":"info","msg":"AudioVideo-Stream has started","time":"2020-01-29T22:35:17+01:00"}
{"level":"error","msg":"Error parsing FEED packet: 6e7973614f23691f0100000064656566b600000066756273200000007374706fd232c5810300000000ca9a3b010000000000000000000000500000006169747301000000000000003c000000010000000000000000000000d232c5810300000000ca9a3b0100000000000000000000000000000000000000000000000000000000000000000000003e000000747461731b0000007679656b0a0000006b786469130009000000766c7562011b0000007679656b0a0000006b786469150009000000766c756201 unknown magic type:ttas (0x73617474), cannot parse value 00000000  3e 00 00 00 74 74 61 73  1b 00 00 00 76 79 65 6b  |\u003e...ttas....vyek|\n00000010  0a 00 00 00 6b 78 64 69  13 00 09 00 00 00 76 6c  |....kxdi......vl|\n00000020  75 62 01 1b 00 00 00 76  79 65 6b 0a 00 00 00 6b  |ub.....vyek....k|\n00000030  78 64 69 15 00 09 00 00  00 76 6c 75 62 01        |xdi......vlub.|\n","time":"2020-01-29T22:35:32+01:00"}
^C{"level":"info","msg":"Telling device to stop streaming..","time":"2020-01-29T22:35:54+01:00"}
{"level":"info","msg":"Waiting for device to tell us to stop..","time":"2020-01-29T22:35:54+01:00"}
{"level":"info","msg":"OK. Ready to release USB Device.","time":"2020-01-29T22:35:54+01:00"}
{"level":"info","msg":"Closing usb stream","time":"2020-01-29T22:35:54+01:00"}
{"level":"info","msg":"Closing usb interface","time":"2020-01-29T22:35:54+01:00"}
{"level":"error","msg":"couldn't read bytesdevice was disconnected","time":"2020-01-29T22:35:54+01:00"}



Something like this? I didn't see a more verbose option. (Also I changed the device ID, but I don't think that should matter).

To be clear, it still seems to work fine, so the error isn't fatal or anything.

**Comment by DanielPaulusContentful** [comment]
Ah cool! Yeah I will check it out. I think I made it an error-log because I wanted to make sure that potentially important things don't go silently unnoticed. If you need the video in any other format btw, let me know, using gstreamer I can add transcoding to mpeg or whatever format is needed or RTP/WebRTC streaming easily.

**Comment by schendstok** [comment]
Cool. The use case I was looking at a couple of months ago is embedding the live-video from an iPad inside a HTML page for a presentation (using a similar looking presentation tool that you used to explain the reverse engineering). I couldn't figure out if I could do that with QuickTime directly and was interested in how it all worked, so did some experiments with AVFoundation on macOS based on: https://nadavrub.wordpress.com/2015/07/06/macos-media-capture-using-coremediaio/
So if you can add a similar kind of streaming through WebRTC, I can see that that could be useful. 

I'm still not entirely sure what QuickTime itself does when it captures an iOS screen (what do the "best" and "maximum" quality settings do? Does QuickTime automatically transcode, or just store an incoming H264 stream? That kind of stuff).

Another cool use case could be to use a Raspberry Pi as an open-source HDMI dongle for Apple devices with lightning-ports, without needing to go through an AirPlay network layer.
So similar to what RPiPlay does, but directly through the USB connection: https://github.com/FD-/RPiPlay

**Comment by danielpaulus** [comment]
I am working on exposing the gstreamer AppSrc on this branch: addCustomGstPipelines
When it is done, I will provide a few example Gstreamer Pipelines that will be customizable easily to modify transcoding settings, video quality etc. 

Quicktime really only puts the raw h264 stream and the raw pcm audio into a mov container without any transcoding, this is also why the files are ridiculously large :-D
The Best and Maximum settings I have not yet investigated but I am also interested whether they actually change some setting on the device. 

That use case is actually pretty cool! Due to the fact that my tool outputs JSON, it should be trivial to build some fancy JavaScript Server around it and automtically detect and create video streams from a raspbi. I will be presenting this thing at a meetup in two weeks, if I find the time I'll try to build something like that :-)
